// apps/client/angular/src/modules/article/components/comment-creator/comment-creator.component.ts
import { CommonModule } from '@angular/common';
import { ChangeDetectionStrategy, Component, inject } from '@angular/core';
import { intersectResults$ } from '@ngneat/query';
import { combineLatest, firstValueFrom } from 'rxjs';

import { CreateCommentSchema } from '@realworld/dto';

import { AvatarComponent } from '../../../../common/components/avatar/avatar.component';
import { AuthService } from '../../../auth/services/auth.service';
import { ArticleService } from '../../services/article.service';
import { CommentComponent } from '../comment/comment.component';
import { CommentShellComponent } from '../comment-shell/comment-shell.component';

@Component({
  selector: 'realworld-comment-creator',
  imports: [CommonModule, AvatarComponent, CommentShellComponent, CommentComponent],
  templateUrl: './comment-creator.component.html',
  styleUrl: './comment-creator.component.scss',
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class CommentCreatorComponent {
  public readonly articleService = inject(ArticleService);

  public readonly data$ = combineLatest({
    user: inject(AuthService).userQuery$,
    comments: this.articleService.commentsQuery$,
  }).pipe(intersectResults$((data) => ({ ...data, user: data.user.user })));

  public async submitComment(e: SubmitEvent) {
    e.preventDefault();

    const slug = await firstValueFrom(this.articleService.slug$);
    if (!slug) return;

    const form = e.target;
    if (!(form instanceof HTMLFormElement)) return;

    const formData = new FormData(form);
    const comment = CreateCommentSchema.parse({
      body: formData.get('body') || undefined,
    });

    await this.articleService.createCommentMut.mutateAsync({ slug, comment });

    form.reset();
  }
}

@if (data$ | async; as result) { @if (articleService.createCommentMut.result$ | async; as
createComment) {
<div class="space-y-4">
  @if (result.isSuccess) {
  <!-- comment creator -->
  <form (submit)="submitComment($event)">
    <realworld-comment-shell>
      <textarea
        name="body"
        rows="4"
        class="w-full textarea textarea-ghost"
        placeholder="Write a comment…"
      ></textarea>

      <ng-container actions>
        <div class="flex items-center justify-between w-full">
          <!-- author -->
          <realworld-avatar size="sm" [user]="result.data.user" />

          <!-- action -->
          <button class="btn btn-primary btn-sm" [disabled]="createComment.isPending">
            @if (createComment.isPending) {
            <div class="loading loading-spinner"></div>
            }
            <span>Post Comment</span>
          </button>
        </div>
      </ng-container>
    </realworld-comment-shell>
  </form>
  }

  <!-- skeleton -->
  @if (createComment.isPending || result.isFetching) {
  <realworld-comment />
  }
</div>
} }

// apps/client/vue/src/modules/article/components/comment-creator.vue
<script setup lang="ts">
import { CreateCommentSchema, type Article } from '@realworld/dto';
import { useCreateComment } from '../../../api/hooks/comment.create';
import { useUser } from '../../../api/hooks/user.get';
import { toRef } from 'vue';
import CommentShell from './comment-shell.vue';
import { Avatar } from '../../../common/components/avatar';
import Comment from './comment.vue';

const props = defineProps<{ slug: Article['slug'] }>();
const slug = toRef(props, 'slug');

const { user } = useUser();

const { mutateAsync: postComment, isPending: isCreatePending } = useCreateComment(slug);

const submitComment = async (e: SubmitEvent) => {
  const form = e.target;
  if (!(form instanceof HTMLFormElement)) return;

  const formData = new FormData(form);
  const comment = CreateCommentSchema.parse({
    body: formData.get('comment'),
  });

  if (!comment.body) return;

  await postComment({ params: { slug: slug.value }, body: { comment } });

  form.reset();
};
</script>

<template>
  <div class="space-y-4">
    <!-- comment creator -->
    <CommentShell is="form" v-if="user" @submit.prevent="submitComment($event as SubmitEvent)">
      <textarea
        name="comment"
        rows="4"
        class="textarea textarea-ghost"
        placeholder="Write a comment…"
      />

      <template #actions>
        <div class="flex justify-between w-full">
          <!-- author -->
          <Avatar size="sm" :user="user" />

          <!-- action -->
          <button class="btn btn-primary btn-sm" :disabled="isCreatePending">
            <div v-if="isCreatePending" class="loading loading-spinner" />
            <span>Post Comment</span>
          </button>
        </div>
      </template>
    </CommentShell>

    <!-- skeleton -->
    <Comment v-if="isCreatePending" slug="" />
  </div>
</template>

<style scoped></style>
