// apps/client/react/src/modules/article/components/comment-list/comment-list.tsx
import { Article } from '@realworld/dto';

import useCommentsGet from '../../../common/api/hooks/comments.get';
import CommentItem from '../comment-item/comment-item';

export interface CommentListProps {
  slug?: Article['slug'];
}

export function CommentList({ slug }: CommentListProps) {
  const { comments } = useCommentsGet(slug);

  return (
    <ol className="space-y-4">
      {comments && slug
        ? comments.map((comment) => (
            <CommentItem as="li" key={comment.id} slug={slug} comment={comment} />
          ))
        : Array.from({ length: 3 }).map((_, index) => <CommentItem as="li" key={index} />)}
    </ol>
  );
}

export default CommentList;

// apps/client/vue/src/modules/article/components/comment-list.vue
<script setup lang="ts">
import type { Article } from '@realworld/dto';
import { toRef } from 'vue';
import Comment from './comment.vue';
import { useComments } from '../../../api/hooks/comments.get';

const props = defineProps<{ slug: Article['slug'] }>();
const slug = toRef(props, 'slug');

const { comments } = useComments(slug);
</script>

<template>
  <ol class="space-y-4">
    <!-- skeleton -->
    <template v-if="!comments">
      <Comment :slug="slug" v-for="index in 3" :key="index" />
    </template>

    <!-- comment -->
    <Comment
      v-else
      is="li"
      v-for="comment in comments"
      :key="comment.id"
      :slug="slug"
      :comment="comment"
    />
  </ol>
</template>

<style scoped></style>
