// apps/client/angular/src/modules/article/components/comment-shell/comment-shell.component.ts

import { ChangeDetectionStrategy, Component, ContentChild, TemplateRef } from '@angular/core';

@Component({
  selector: 'realworld-comment-shell',
  imports: [],
  templateUrl: './comment-shell.component.html',
  styleUrl: './comment-shell.component.scss',
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class CommentShellComponent {
  @ContentChild('slot')
  public slot?: TemplateRef<HTMLElement>;
}

<div class="overflow-auto card card-bordered border-base-300 dark:border-neutral">
  <!-- body -->
  <div class="p-0 card-body">
    <ng-content></ng-content>
  </div>

  <!-- actions -->
  <div class="px-5 py-3 card-actions bg-base-200">
    <ng-content select="[actions]"></ng-content>
  </div>
</div>

// apps/client/vue/src/modules/article/components/comment-shell.vue
<script setup lang="ts">
// defineProps<{}>()
</script>

<template>
  <component
    :is="$attrs.is || 'div'"
    class="overflow-auto card card-bordered border-base-300 dark:border-neutral"
  >
    <!-- body -->
    <div class="p-0 card-body">
      <slot></slot>
    </div>

    <!-- actions -->
    <div class="px-5 py-3 card-actions bg-base-200">
      <slot name="actions"></slot>
    </div>
  </component>
</template>

<style scoped></style>
