// apps/client/angular/src/common/components/navbar/navbar.component.ts
import { CommonModule } from '@angular/common';
import { CUSTOM_ELEMENTS_SCHEMA, ChangeDetectionStrategy, Component, inject } from '@angular/core';
import { RouterModule } from '@angular/router';
import { Observable, map } from 'rxjs';

import { AuthModule } from '../../../modules/auth/auth.module';
import { AuthService } from '../../../modules/auth/services/auth.service';
import { AvatarComponent } from '../avatar/avatar.component';

import { Menu, MenuItem } from './navbar.const';

@Component({
  selector: 'realworld-navbar',
  imports: [CommonModule, RouterModule, AuthModule, AvatarComponent],
  templateUrl: './navbar.component.html',
  styleUrl: './navbar.component.scss',
  changeDetection: ChangeDetectionStrategy.OnPush,
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
})
export class NavbarComponent {
  #authService = inject(AuthService);

  public readonly menuItems$: Observable<MenuItem[]> = this.#authService.user$.pipe(
    map((user) => (user ? Menu.private(user) : Menu.public()))
  );
}

<header>
  <div class="flex items-center justify-between max-w-6xl px-4 py-2 mx-auto text-md h-14">
    <!-- logo -->
    <a routerLink="/" class="text-2xl leading-[3.75rem] font-bold text-primary font-title">
      conduit
    </a>

    <!-- menu -->
    <nav>
      <ol class="flex items-center h-full gap-4">
        @for (item of menuItems$ | async; track item.id) {
        <li class="h-full">
          <a
            [routerLink]="item.href"
            routerLinkActive="active !text-base-content/100"
            class="flex items-center h-full space-x-1 text-base-content/60 hover:text-base-content/90"
          >
            @if (item.user) {
            <realworld-avatar [user]="item.user" size="sm"></realworld-avatar>
            } @else if(item.icon) {
            <iconify-icon [icon]="item.icon" class="text-xl"></iconify-icon>
            }
            <span>{{ item.name }}</span>
          </a>
        </li>
        } @empty {
        <span class="text-error">Something went wrong.</span>
        }
      </ol>
    </nav>
  </div>
</header>

// apps/client/react/src/modules/common/components/navbar/navbar.tsx
import classnames from 'classnames';
import { useMemo } from 'react';
import { Link, NavLink } from 'react-router-dom';

import { useUserGet } from '../../api/hooks/user.get';
import { menuItems } from '../../constants/menu-items.const';

/* eslint-disable-next-line */
export interface NavbarProps {}

export function Navbar(props: NavbarProps) {
  const { data, isSuccess } = useUserGet();

  const items = useMemo(
    () => (isSuccess ? menuItems.private(data.user) : menuItems.public()),
    [isSuccess, data]
  );

  return (
    <header>
      <div className="flex items-center justify-between max-w-6xl px-4 py-2 mx-auto text-md h-14">
        {/* logo */}
        <Link to="/" className="text-2xl leading-[3.75rem] font-bold text-primary font-title">
          conduit
        </Link>

        {/* menu */}
        <nav>
          <ol className="flex items-center h-full gap-4">
            {items.map((item) => (
              <li className="h-full" key={item.name}>
                <NavLink
                  to={item.href}
                  className={({ isActive }) =>
                    classnames([
                      'flex items-center h-full space-x-1 text-base-content/60 hover:text-base-content/90',
                      { 'active !text-base-content/100': isActive },
                    ])
                  }
                >
                  {item.icon && <item.icon />}
                  <span>{item.name}</span>
                </NavLink>
              </li>
            ))}
          </ol>
        </nav>
      </div>
    </header>
  );
}

export default Navbar;
