// apps/client/vue/src/modules/article/components/comment.vue
<script setup lang="ts">
import { formatter } from '@realworld/utils';
import CommentShell from './comment-shell.vue';
import { useUser } from '../../../api/hooks/user.get';
import { useDeleteComment } from '../../../api/hooks/comment.delete';
import type { Article, Comment } from '@realworld/dto';
import IconDelete from 'virtual:icons/ion/trash-a';
import { toRef } from 'vue';
import { Avatar } from '../../../common/components/avatar';

const props = defineProps<{ slug: Article['slug']; comment?: Comment }>();
const slug = toRef(props, 'slug');

const { user } = useUser();

const { mutate: deleteComment, isPending: isDeletePending } = useDeleteComment(slug);
</script>

<template>
  <!-- skeleton -->
  <div v-if="!comment" class="w-full h-40 skeleton" />

  <CommentShell v-else :is="$attrs.is || 'div'">
    <!-- text -->
    <div class="p-4">{{ comment.body }}</div>

    <!-- actions -->
    <template #actions>
      <div class="flex justify-between w-full">
        <div class="flex items-center space-x-1 text-sm font-light">
          <!-- author -->
          <Avatar size="sm" :user="comment.author" />
          <router-link
            :to="`/profile/${comment.author.username}`"
            class="text-primary hover:link link-primary"
          >
            {{ comment.author.username }}
          </router-link>
          <span>{{ formatter.format(new Date(comment.updatedAt)) }}</span>
        </div>

        <!-- delete comment -->
        <button
          v-if="comment.author.username === user?.username"
          class="btn btn-ghost btn-square btn-sm"
          @click="deleteComment({ params: { id: comment.id, slug } })"
          :disabled="isDeletePending"
        >
          <div v-if="isDeletePending" class="loading loading-spinner" />
          <IconDelete v-else />
        </button>
      </div>
    </template>
  </CommentShell>
</template>

<style scoped></style>

// apps/client/angular/src/modules/article/components/comment/comment.component.ts
import { CommonModule } from '@angular/common';
import {
  CUSTOM_ELEMENTS_SCHEMA,
  ChangeDetectionStrategy,
  Component,
  Input,
  inject,
} from '@angular/core';
import { RouterModule } from '@angular/router';
import { combineLatest } from 'rxjs';

import { Comment } from '@realworld/dto';

import { AvatarComponent } from '../../../../common/components/avatar/avatar.component';
import { AuthService } from '../../../auth/services/auth.service';
import { ArticleService } from '../../services/article.service';
import { CommentShellComponent } from '../comment-shell/comment-shell.component';

@Component({
  selector: 'realworld-comment',
  imports: [CommonModule, RouterModule, CommentShellComponent, AvatarComponent],
  templateUrl: './comment.component.html',
  styleUrl: './comment.component.scss',
  changeDetection: ChangeDetectionStrategy.OnPush,
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
})
export class CommentComponent {
  @Input()
  public slug?: string | null;

  @Input()
  public comment!: Comment;

  public readonly articleService = inject(ArticleService);

  public readonly data$ = combineLatest({
    user: inject(AuthService).user$,
    slug: this.articleService.slug$,
  });
}

<!-- skeleton -->
@if (!comment) {
<div class="w-full h-40 skeleton"></div>
} @else {
<realworld-comment-shell>
  <!-- text -->
  <div class="p-4">{{ comment.body }}</div>

  <!-- actions -->
  <ng-container actions>
    <div class="flex justify-between w-full">
      <div class="flex items-center space-x-1 text-sm font-light">
        <!-- author -->
        <realworld-avatar size="sm" [user]="comment.author" />
        <a
          [routerLink]="['profile', comment.author.username]"
          [relativeTo]="null"
          class="text-primary hover:link link-primary"
        >
          {{ comment.author.username }}
        </a>
        <span>{{ comment.updatedAt | date : 'MMM d, y' }}</span>
      </div>

      <!-- delete comment -->
      @if(data$ | async; as data) { @if (articleService.deleteComment$ | async; as deleteComment) {
      @if (comment.author.username === data.user?.username && data.slug) {
      <button
        class="btn btn-ghost btn-square btn-sm"
        (click)="deleteComment.mutate({ slug: data.slug, id: comment.id })"
        [disabled]="deleteComment.isPending"
      >
        @if (deleteComment.isPending) {
        <div class="loading loading-spinner"></div>
        } @else {
        <iconify-icon icon="ion:trash-b" class="text-xl"></iconify-icon>
        }
      </button>
      }}}
    </div>
  </ng-container>
</realworld-comment-shell>
}
