// apps/client/angular/src/modules/article/components/article-item/article-item.component.ts
import { CommonModule } from '@angular/common';
import { ChangeDetectionStrategy, Component, Input } from '@angular/core';
import { RouterModule } from '@angular/router';

import { Article } from '@realworld/dto';

import { AuthorComponent } from '../../../../common/components/author/author.component';
import { LikeComponent } from '../../../../common/components/like/like.component';

@Component({
  selector: 'realworld-article-item',
  imports: [CommonModule, RouterModule, AuthorComponent, LikeComponent],
  templateUrl: './article-item.component.html',
  styleUrl: './article-item.component.scss',
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class ArticleItemComponent {
  @Input()
  public article!: Article;

  public readonly wrapperClass = 'py-6 border-t border-t-neutral';
}

@if (!article) {
<!-- skeleton -->
<div [ngClass]="[wrapperClass, 'flex flex-col w-full gap-4']">
  <realworld-author />

  <div class="h-6 w-80 skeleton"></div>
  <div class="h-4 skeleton w-96"></div>
  <div class="flex items-center justify-between">
    <div class="h-3 w-28 skeleton"></div>
    <div class="w-64 h-4 skeleton"></div>
  </div>
</div>
} @else {
<!-- article -->
<div
  [ngClass]="[
    wrapperClass,
    'grid grid-areas-[author_likes,article_article] grid-cols-[1fr_auto] gap-y-4'
  ]"
>
  <!-- author -->
  <realworld-author
    [author]="article.author"
    [createdAt]="article.createdAt"
    class="grid grid-in-[author]"
  />

  <!-- likes -->
  <realworld-like [article]="article" class="grid-in-[likes]" />

  <!-- article -->
  <a [routerLink]="['article', article.slug]" [relativeTo]="null" class="grid-in-[article]">
    <h2 class="mb-1 text-2xl">{{ article.title }}</h2>
    <p class="mb-4 text-base leading-5 text-base-content/50">
      {{ article.description }}
    </p>

    <div class="flex items-center justify-between text-base-content/50">
      <span class="text-xs">Read more…</span>
      <ul class="flex space-x-1">
        @for (tag of article.tagList; track tag) {
        <li class="badge badge-outline">{{ tag }}</li>
        }
      </ul>
    </div>
  </a>
</div>
}

// apps/client/react/src/modules/article/components/article-item/article-item.tsx
import classNames from 'classnames';
import { Link } from 'react-router-dom';

import { Article } from '@realworld/dto';

import Author from '../../../common/components/author/author';
import Like from '../../../common/components/like/like';

export interface ArticleItemProps {
  as: keyof HTMLElementTagNameMap;
  article?: Article;
}

export function ArticleItem({ as: Component, article, ...rest }: ArticleItemProps) {
  const wrapperClass = 'py-6 border-t border-t-neutral';

  return article ? (
    <Component
      className={classNames([
        wrapperClass,
        'grid grid-areas-[author_likes,article_article] grid-cols-[1fr_auto] gap-y-4',
      ])}
      {...rest}
    >
      <Author
        author={article?.author}
        createdAt={article?.createdAt}
        className="grid grid-in-[author]"
      />

      <Like article={article} className="grid-in-[likes]" />

      <Link to={`/article/${article.slug}`} className="grid-in-[article]">
        <h2 className="mb-1 text-2xl">{article.title}</h2>
        <p className="mb-4 text-base leading-5 text-base-content/50">{article.description}</p>

        <div className="flex items-center justify-between text-base-content/50">
          <span className="text-xs">Read more…</span>
          <ul className="flex space-x-1">
            {article.tagList.map((tag) => (
              <li key={tag} className="badge badge-outline">
                {tag}
              </li>
            ))}
          </ul>
        </div>
      </Link>
    </Component>
  ) : (
    <Component className={classNames([wrapperClass, 'flex flex-col w-full gap-4'])} {...rest}>
      <Author />

      <div className="h-6 w-80 skeleton"></div>
      <div className="h-4 skeleton w-96"></div>
      <div className="flex items-center justify-between">
        <div className="h-3 w-28 skeleton"></div>
        <div className="w-64 h-4 skeleton"></div>
      </div>
    </Component>
  );
}

export default ArticleItem;
