// apps/client/react/src/modules/common/components/follow/follow.tsx
import classNames from 'classnames';
import IconRemove from 'virtual:icons/ion/minus-round';
import IconAdd from 'virtual:icons/ion/plus-round';

import { Profile } from '@realworld/dto';

import useProfileGet from '../../api/hooks/profile.get';
import useToggleFollow from '../../api/hooks/toggle-follow';
import { useUserGet } from '../../api/hooks/user.get';

export interface FollowProps {
  username: Profile['username'];
  contrast?: boolean;
}

export function Follow({ username, contrast }: FollowProps) {
  const { user } = useUserGet();
  const { profile, isFetching: profile_isPending } = useProfileGet(username);
  const { toggleFollow, isPending } = useToggleFollow(profile);

  return profile ? (
    <button
      className={classNames([
        'btn btn-outline btn-sm',
        {
          'text-neutral-content hover:text-neutral hover:bg-neutral-content': contrast,
        },
        { 'btn-active active': profile.following },
      ])}
      disabled={!user || user.username === profile.username || isPending || profile_isPending}
      onClick={toggleFollow}
    >
      <slot>
        {profile.following ? <IconRemove /> : <IconAdd />}
        <span>
          {profile.following ? 'Unfollow ' : 'Follow '}
          {profile.username}
        </span>
      </slot>
    </button>
  ) : (
    <div className="w-10 h-4 skeleton" />
  );
}

export default Follow;

// apps/client/angular/src/common/components/follow/follow.component.ts
import { CommonModule } from '@angular/common';
import {
  CUSTOM_ELEMENTS_SCHEMA,
  ChangeDetectionStrategy,
  Component,
  Input,
  inject,
} from '@angular/core';
import classNames from 'classnames';

import { Profile } from '@realworld/dto';

import { AuthService } from '../../../modules/auth/services/auth.service';
import { UserService } from '../../../modules/user/services/user.service';

@Component({
  selector: 'realworld-follow',
  imports: [CommonModule],
  templateUrl: './follow.component.html',
  styleUrl: './follow.component.scss',
  changeDetection: ChangeDetectionStrategy.OnPush,
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
})
export class FollowComponent {
  public readonly classNames = classNames;

  @Input()
  public contrast = false;

  @Input()
  public profile?: Profile | null = null;

  public readonly authService = inject(AuthService);
  public readonly userService = inject(UserService);
}

@if (authService.userQuery$ | async; as user) { @if (user.isPending ) {
<!-- skeleton -->
<div class="h-8 w-36 skeleton"></div>
} @else if(profile) {
<!-- button -->
<button
  [class]="classNames([
      'btn btn-outline btn-sm',
      {
        'text-neutral-content hover:text-neutral hover:bg-neutral-content':
          contrast,
      },
      { 'btn-active active': profile.following},
    ])"
  [disabled]="user.data?.user?.username === profile.username || user.isFetching"
  (click)="userService.toggleFollow(profile)"
>
  <slot>
    @if (profile.following) {
    <iconify-icon icon="ion:minus-round"></iconify-icon>
    } @else {
    <iconify-icon icon="ion:plus-round"></iconify-icon>
    }
    <span>
      {{ profile.following ? 'Unfollow' : 'Follow' }}
      {{ profile.username }}
    </span>
  </slot>
</button>
}}
