// apps/client/angular/src/app/components/app/app.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'realworld-root',
  templateUrl: './app.component.html',
  styleUrl: './app.component.scss',
})
export class AppComponent {}

<!-- nav -->
<realworld-navbar></realworld-navbar>

<!-- header -->
<realworld-app-header></realworld-app-header>

<!-- content -->
<main class="max-w-6xl px-4 mx-auto">
  <router-outlet></router-outlet>
</main>

// apps/client/react/src/app/app.tsx
import { ReactNode, useState } from 'react';
import { Outlet } from 'react-router-dom';

import Navbar from '../modules/common/components/navbar/navbar';

export function App() {
  const [header, setHeader] = useState<ReactNode>(null);

  return (
    <div>
      <Navbar />

      {header}

      <main className="max-w-6xl px-4 mx-auto ">
        <Outlet context={{ setHeader }}></Outlet>
      </main>
    </div>
  );
}

export default App;
