// apps/client/vue/src/common/components/author.vue
<script setup lang="ts">
import type { Article } from '@realworld/dto';
import { formatter } from '@realworld/utils';
import { Avatar } from './avatar';

const props = defineProps<{
  author?: Article['author'];
  createdAt: Article['createdAt'];
}>();
</script>

<template>
  <!-- skeleton -->
  <div v-if="!props.author" :class="['flex items-center gap-4', $attrs.class]">
    <Avatar :user="null" size="md" />
    <div class="flex flex-col gap-2">
      <div class="h-4 w-14 skeleton"></div>
      <div class="w-24 h-3 skeleton"></div>
    </div>
  </div>

  <!-- author -->
  <div
    v-else
    :class="[
      'grid grid-areas-[avatar_name,avatar_created] grid-cols-[auto,1fr] gap-x-2 items-center w-fit',
      $attrs.class,
    ]"
  >
    <!-- avatar -->
    <Avatar :user="props.author" size="md" class="grid-in-[avatar]" />

    <!-- username -->
    <router-link
      :to="`/profile/${props.author.username}`"
      class="grid-in-[name] hover:link text-primary link-primary w-fit"
    >
      {{ props.author.username }}
    </router-link>
    <!-- article createdAt -->
    <span
      class="grid-in-[created] text-xs text-base-300 dark:text-base-content/50"
    >
      {{ formatter.format(new Date(props.createdAt)) }}
    </span>
  </div>
</template>

<style scoped></style>

// apps/client/angular/src/common/components/author/author.component.ts
import { CommonModule } from '@angular/common';
import { ChangeDetectionStrategy, Component, Input } from '@angular/core';
import { RouterModule } from '@angular/router';

import { Article, Profile } from '@realworld/dto';

import { AvatarComponent } from '../avatar/avatar.component';

@Component({
  selector: 'realworld-author',
  imports: [CommonModule, RouterModule, AvatarComponent],
  templateUrl: './author.component.html',
  styleUrl: './author.component.scss',
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class AuthorComponent {
  @Input()
  public author!: Profile;

  @Input()
  public createdAt!: Article['createdAt'];
}

@if (!author) {
<!-- skeleton -->
<div class="flex items-center gap-4">
  <realworld-avatar size="md" />
  <div class="flex flex-col gap-2">
    <div class="h-4 w-14 skeleton"></div>
    <div class="w-24 h-3 skeleton"></div>
  </div>
</div>
} @else {
<!-- author -->
<div
  class="grid grid-areas-[avatar_name,avatar_created] grid-cols-[auto,1fr] gap-x-2 items-center w-fit"
>
  <!-- avatar -->
  <realworld-avatar [user]="author" size="md" class="grid-in-[avatar]" />

  <!-- username -->
  <a
    [routerLink]="['profile', author.username]"
    [relativeTo]="null"
    class="grid-in-[name] hover:link text-primary link-primary w-fit"
  >
    {{ author.username }}
  </a>

  <!-- article createdAt -->
  <span class="grid-in-[created] text-xs text-base-300 dark:text-base-content/50">
    {{ createdAt | date : 'MMM d, y' }}
  </span>
</div>
}
