// apps/client/vue/src/common/components/tabs.vue
<script setup lang="ts">
import type { FunctionalComponent, SVGAttributes } from 'vue';

export interface Tab {
  id: string;
  label: string;
  href?: string;
  icon?: FunctionalComponent<SVGAttributes, {}, any>;
}

defineProps<{ tabs: Tab[]; selected: Tab['id'] }>();
defineEmits<{ 'update:selected': [id: Tab['id']] }>();
</script>

<template>
  <div>
    <div role="tablist" class="tabs tabs-bordered">
      <a
        role="tab"
        :class="[
          'tab gap-1 tab-border-none',
          {
            'tab-active active text-primary [--bc:none]': tab.id === selected,
          },
        ]"
        v-for="tab in tabs"
        :key="tab.id"
        @click="$emit('update:selected', tab.id)"
      >
        <component :is="tab.icon" v-if="tab.icon"></component>
        <span>{{ tab.label }}</span>
      </a>
    </div>
  </div>
</template>

<style scoped></style>

// apps/client/react/src/modules/article/components/tabs/tabs.tsx
import classNames from 'classnames';
import { HTMLProps } from 'react';
import { NavLink } from 'react-router-dom';

export interface Tab {
  id: string;
  href?: string;
  label: string;
  icon?: JSX.Element;
}

export interface TabsProps extends HTMLProps<HTMLOListElement> {
  tabs: Tab[];
}

export function Tabs({ tabs, className }: TabsProps) {
  return (
    <div role="tablist" className={classNames([className, 'tabs tabs-bordered'])}>
      {tabs.map((tab) => (
        <NavLink
          to={tab.href ?? tab.id}
          key={tab.id}
          role="tab"
          end
          className={({ isActive }) =>
            classNames([
              'tab gap-1 tab-border-none',
              { 'tab-active active text-primary [--bc:none]': isActive },
            ])
          }
        >
          {tab.icon && tab.icon}
          <span>{tab.label}</span>
        </NavLink>
      ))}
    </div>
  );
}

export default Tabs;
