// apps/client/vue/src/modules/article/components/impression.vue
<script setup lang="ts">
import type { Article } from '@realworld/dto';
import Author from '../../../common/components/author.vue';
import IconHeart from 'virtual:icons/ion/heart';
import Like from '../../../common/components/like.vue';
import { useUser } from '../../../api/hooks/user.get';
import Follow from '../../../common/components/follow.vue';

defineProps<{ article?: Article; contrast?: boolean }>();

const { user } = useUser();

const wrapperClass = 'flex space-x-6';
</script>

<template>
  <!-- skeleton -->
  <div v-if="!article" :class="[wrapperClass, $attrs.class]">
    <Author created-at="" />
    <div class="h-8 w-36 skeleton" />
    <div class="h-8 w-36 skeleton" />
  </div>

  <!-- content -->
  <div v-else :class="[wrapperClass, $attrs.class]">
    <!-- author -->
    <Author :author="article.author" :created-at="article.createdAt" />

    <!-- actions -->
    <div class="flex items-center space-x-2">
      <!-- follow author -->
      <Follow :username="article.author.username" />

      <!-- like article -->
      <Like :article="article" class="!btn-sm">
        <IconHeart />
        <span v-if="user">Favorite Article</span>
        <span> {{ article.favoritesCount }}</span>
      </Like>
    </div>
  </div>
</template>

<style scoped></style>

// apps/client/angular/src/modules/article/components/impression/impression.component.ts
import { CommonModule } from '@angular/common';
import {
  CUSTOM_ELEMENTS_SCHEMA,
  ChangeDetectionStrategy,
  Component,
  Input,
  inject,
} from '@angular/core';

import { Article } from '@realworld/dto';

import { AuthorComponent } from '../../../../common/components/author/author.component';
import { FollowComponent } from '../../../../common/components/follow/follow.component';
import { LikeComponent } from '../../../../common/components/like/like.component';
import { AuthService } from '../../../auth/services/auth.service';

@Component({
  selector: 'realworld-impression',
  imports: [CommonModule, LikeComponent, FollowComponent, AuthorComponent],
  templateUrl: './impression.component.html',
  styleUrl: './impression.component.scss',
  changeDetection: ChangeDetectionStrategy.OnPush,
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
})
export class ImpressionComponent {
  @Input()
  public article: Article | null | undefined = null;

  public readonly userQuery$ = inject(AuthService).userQuery$;
}

@if (userQuery$ | async; as user) { @if (!article) {
<!-- skeleton -->
<div class="wrapper">
  <realworld-author />
  <div class="h-8 w-36 skeleton"></div>
  <div class="h-8 w-36 skeleton"></div>
</div>
} @else {
<!-- content -->
<div class="wrapper">
  <!-- author -->
  <realworld-author [author]="article.author" [createdAt]="article.createdAt" />

  <!-- actions -->
  <div class="flex items-center space-x-2">
    <!-- follow author -->
    <realworld-follow [profile]="article.author" [contrast]="true" />

    <!-- like article -->
    <realworld-like [article]="article" btnClass="!btn-sm">
      <ng-template #slot>
        <iconify-icon icon="ion:heart"></iconify-icon>
        @if (user.isSuccess) {
        <span>{{ article.favorited ? 'Unfavorite' : 'Favorite' }} Article</span>
        }
        <span>({{ article.favoritesCount }})</span>
      </ng-template>
    </realworld-like>
  </div>
</div>
} }
