// apps/client/vue/src/modules/article/pages/create-article.page.vue
<script setup lang="ts">
import { CreateArticleSchema } from '@realworld/dto';
import { useCreateArticle } from '../../../api/hooks/article.create';

const { mutate, isPending } = useCreateArticle();

const submit = (e: SubmitEvent) => {
  const form = e.target;
  if (!(form instanceof HTMLFormElement)) return;

  const formData = new FormData(form);
  const article = CreateArticleSchema.parse({
    title: formData.get('title'),
    description: formData.get('description'),
    body: formData.get('body'),
    tagList:
      formData
        .get('tagList')
        ?.toString()
        .split(',')
        .map((s) => s.trim()) ?? [],
  });

  mutate({ body: { article } });
};
</script>

<template>
  <form
    ref="form"
    @submit.prevent="submit($event as SubmitEvent)"
    class="flex flex-col w-full max-w-4xl gap-4 mt-8"
  >
    <input
      name="title"
      type="text"
      class="input input-bordered input-lg"
      placeholder="Article title"
      :disabled="isPending"
    />
    <input
      name="description"
      type="text"
      class="input input-bordered"
      placeholder="What's this article about?"
      :disabled="isPending"
    />
    <textarea
      name="body"
      rows="8"
      class="textarea textarea-bordered"
      placeholder="Write your article (in markdown)"
      :disabled="isPending"
    />
    <input
      name="tagList"
      type="text"
      class="input input-bordered"
      placeholder="Enter tags"
      :disabled="isPending"
    />

    <button class="btn btn-primary btn-lg place-self-end" :disabled="isPending">
      <div v-if="isPending" class="loading loading-spinner"></div>
      <span>Publish Article</span>
    </button>
  </form>
</template>

<style scoped></style>

// apps/client/angular/src/modules/article/pages/create/create-article.page.ts
import { CommonModule } from '@angular/common';
import { ChangeDetectionStrategy, Component, inject } from '@angular/core';

import { CreateArticleSchema } from '@realworld/dto';

import { ArticleService } from '../../services/article.service';

@Component({
  selector: 'realworld-create-article',
  imports: [CommonModule],
  templateUrl: './create-article.page.html',
  styleUrl: './create-article.page.scss',
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class CreateArticlePage {
  public readonly articleService = inject(ArticleService);

  public async submit(e: SubmitEvent) {
    e.preventDefault();

    const form = e.target;
    if (!(form instanceof HTMLFormElement)) return;

    const formData = new FormData(form);
    const article = CreateArticleSchema.parse({
      title: formData.get('title'),
      description: formData.get('description'),
      body: formData.get('body'),
      tagList:
        formData
          .get('tagList')
          ?.toString()
          .split(',')
          .map((s) => s.trim())
          .filter(Boolean) ?? [],
    });

    await this.articleService.createArticleMut.mutateAsync(article);

    form.reset();
  }
}
