// apps/client/vue/src/modules/article/components/impression.vue
<script setup lang="ts">
import type { Article } from '@realworld/dto';
import Author from '../../../common/components/author.vue';
import IconHeart from 'virtual:icons/ion/heart';
import Like from '../../../common/components/like.vue';
import { useUser } from '../../../api/hooks/user.get';
import Follow from '../../../common/components/follow.vue';

defineProps<{ article?: Article; contrast?: boolean }>();

const { user } = useUser();

const wrapperClass = 'flex space-x-6';
</script>

<template>
  <!-- skeleton -->
  <div v-if="!article" :class="[wrapperClass, $attrs.class]">
    <Author created-at="" />
    <div class="h-8 w-36 skeleton" />
    <div class="h-8 w-36 skeleton" />
  </div>

  <!-- content -->
  <div v-else :class="[wrapperClass, $attrs.class]">
    <!-- author -->
    <Author :author="article.author" :created-at="article.createdAt" />

    <!-- actions -->
    <div class="flex items-center space-x-2">
      <!-- follow author -->
      <Follow :username="article.author.username" />

      <!-- like article -->
      <Like :article="article" class="!btn-sm">
        <IconHeart />
        <span v-if="user">Favorite Article</span>
        <span> {{ article.favoritesCount }}</span>
      </Like>
    </div>
  </div>
</template>

<style scoped></style>

// apps/client/react/src/modules/common/components/impression/impression.tsx
import classNames from 'classnames';
import { HTMLAttributes } from 'react';
import IconHeart from 'virtual:icons/ion/heart';

import { Article } from '@realworld/dto';

import { useUserGet } from '../../api/hooks/user.get';
import Author from '../author/author';
import Follow from '../follow/follow';
import Like from '../like/like';

export interface ImpressionProps extends HTMLAttributes<HTMLElement> {
  article?: Article;
}

export function Impression({ className, article }: ImpressionProps) {
  const wrapperClass = 'flex space-x-6';
  const { isSuccess } = useUserGet();

  return article ? (
    <div className={classNames([wrapperClass, className])}>
      <Author author={article.author} createdAt={article.createdAt} />

      <div className="flex items-center space-x-2">
        <Follow username={article.author.username} />

        <Like article={article} className="!btn-sm">
          <IconHeart />
          {isSuccess && <span>Favorite Article</span>}
          <span> {article.favoritesCount}</span>
        </Like>
      </div>
    </div>
  ) : (
    <div className={classNames([wrapperClass, className])}>
      <Author />
      <div className="h-8 w-36 skeleton" />
      <div className="h-8 w-36 skeleton" />
    </div>
  );
}

export default Impression;
