// apps/client/angular/src/common/components/like/like.component.ts
import { CommonModule } from '@angular/common';
import {
  CUSTOM_ELEMENTS_SCHEMA,
  ChangeDetectionStrategy,
  Component,
  ContentChild,
  Input,
  TemplateRef,
  inject,
} from '@angular/core';
import classNames from 'classnames';

import { Article } from '@realworld/dto';

import { ArticleService } from '../../../modules/article/services/article.service';
import { AuthService } from '../../../modules/auth/services/auth.service';

@Component({
  selector: 'realworld-like',
  imports: [CommonModule],
  templateUrl: './like.component.html',
  styleUrl: './like.component.scss',
  changeDetection: ChangeDetectionStrategy.OnPush,
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
})
export class LikeComponent {
  public readonly classNames = classNames;

  @Input()
  public article?: Article;

  @Input()
  public btnClass?: string;

  @ContentChild('slot')
  public slot?: TemplateRef<HTMLElement>;

  public readonly authService = inject(AuthService);
  public readonly articleService = inject(ArticleService);
}

@if (authService.userQuery$ | async; as user) { @if (!article) {
<!-- skeleton -->
<div class="w-10 h-4 skeleton"></div>
} @else {
<!-- button -->
<button
  [class]="
    classNames([
      'btn btn-xs btn-outline btn-primary min-w-[4rem]',
      { 'disabled:btn-primary': !user.isSuccess },
      { 'btn-active active': article.favorited },
      btnClass
    ])
  "
  [disabled]="!user.isSuccess"
  (click)="articleService.toggleLike(article)"
>
  <ng-container [ngTemplateOutlet]="slot || default"></ng-container>

  <ng-template #default>
    <iconify-icon icon="ion:heart"></iconify-icon>
    <span>{{ article.favoritesCount }}</span>
  </ng-template>
</button>
} }

// apps/client/react/src/modules/common/components/like/like.tsx
import classNames from 'classnames';
import { HTMLAttributes } from 'react';
import IconHeart from 'virtual:icons/ion/heart';

import { Article } from '@realworld/dto';

import useToggleFavorite from '../../api/hooks/toggle-favorite';
import { useUserGet } from '../../api/hooks/user.get';

export interface LikeProps extends HTMLAttributes<HTMLButtonElement> {
  article?: Article;
}

export function Like({ article, className }: LikeProps) {
  const { user } = useUserGet();
  const { toggleLike } = useToggleFavorite(article);

  return article ? (
    <button
      className={classNames([
        'btn btn-xs btn-outline btn-primary min-w-[4rem]',
        { 'disabled:btn-primary': !user },
        { 'btn-active active': article.favorited },
        className,
      ])}
      disabled={!user}
      onClick={toggleLike}
    >
      <IconHeart />
      <span>{article.favoritesCount}</span>
    </button>
  ) : (
    <div className="w-10 h-4 skeleton" />
  );
}

export default Like;
